spring.application.name=template-project-docker

spring.docker.compose.enabled=true
spring.docker.compose.file=docker-compose-dev.yml

app.debug.logging.enabled=true

# Observability config
management.opentelemetry.resource-attributes.app-version=@project.version@
management.observations.annotations.enabled=true

## Logging
logging.structured.format.console=logstash

management.logging.export.otlp.enabled=true
management.opentelemetry.logging.export.otlp.endpoint=http://localhost:4317
management.opentelemetry.logging.export.otlp.transport=grpc

## Metrics
management.otlp.metrics.export.enabled=true
management.otlp.metrics.export.step=10s
management.otlp.metrics.export.url=http://localhost:4318/v1/metrics

## Traces
management.tracing.export.enabled=true
management.tracing.export.otlp.enabled=true
management.tracing.sampling.probability=1.0

management.opentelemetry.tracing.export.otlp.transport=grpc
management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4317
