version: '3'
services:
  server:
    container_name: example-server
    build:
      dockerfile: Dockerfile
    image: example-server:latest
    environment:
      - "spring.profiles.active=dev"
    ports:
      - "8080:8080"
    networks:
      - example-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/up" ]
      interval: 1m30s
      timeout: 10s
      retries: 3

networks:
  example-network:
    driver: bridge
