version: '3.8'
services:
  server:
    container_name: example-server
    build:
      dockerfile: Dockerfile
    image: example-server:latest
    environment:
      - "spring.profiles.active=dev"
    ports:
      - "8080:8080"
    networks:
      - example-network
    healthcheck:
      test: [ "CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  example-network:
    driver: bridge
