version: '3.8'
name: template-app-dev-setup
services:
  database:
    image: postgres:latest
    environment:
      - POSTGRES_DB=example
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=12345
    ports:
      - "5432:5432"
    networks:
      - example-network

  pgAdmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=12345
    ports:
      - "8070:80"
    networks:
      - example-network

  prometheus:
    image: prom/prometheus:latest
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - example-network

  grafana:
    image: grafana/grafana:latest
    configs:
      - source: grafana_datasource_config
        target: /etc/grafana/provisioning/datasources/datasources.yml
      - source: grafana_dashboard_config
        target: /etc/grafana/provisioning/dashboards/main.yaml
    volumes:
      - ./.grafana/example-dashboard.json:/var/lib/grafana/dashboards/dashboard.json
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - example-network

networks:
  example-network:
    driver: bridge

configs:
  prometheus_config:
    content: |
      scrape_configs:
        - job_name: 'spring-actuator'
          metrics_path: '/actuator/prometheus'
          scrape_interval: '10s'
          static_configs:
            - targets: ['host.docker.internal:8080']
              labels:
                application: 'template-app'

  grafana_datasource_config:
    content: |
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://prometheus:9090
          isDefault: true
          editable: false

  grafana_dashboard_config:
    content: |
      apiVersion: 1
      providers:
        - name: Dashboard provider
          allowUiUpdates: true
          options:
            path: /var/lib/grafana/dashboards
            foldersFromFilesStructure: true
