openapi: 3.1.0
info:
  title: OpenAPI definition
  version: v0
servers:
- description: Generated server url
  url: http://localhost:8080
paths:
  /example:
    get:
      operationId: getExamples
      parameters:
      - description: Zero-based page index (0..N)
        in: query
        name: page
        schema:
          default: 0
          example: null
      - description: The size of the page to be returned
        in: query
        name: size
        schema:
          default: 20
          example: null
      - description: "Sorting criteria in the format: property,(asc|desc). Default\
          \ sort order is ascending. Multiple sort criteria are supported."
        in: query
        name: sort
        schema:
          type:
          - array
          example: null
          items:
            example: null
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PageDetailsExampleDTO"
                example: null
          description: The Example list has been successfully returned.
      summary: Gets paginated and sorted Examples.
      tags:
      - example-controller
    post:
      operationId: createExample
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ExampleDTO"
              example: null
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                type:
                - array
                example: null
                items:
                  $ref: "#/components/schemas/ExampleDTO"
                  example: null
          description: Example successfully created.
      summary: Creates a new Example.
      tags:
      - example-controller
    put:
      operationId: updateExample
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ExampleDTO"
              example: null
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                type:
                - array
                example: null
                items:
                  $ref: "#/components/schemas/ExampleDTO"
                  example: null
          description: Example successfully updated.
        "404":
          content:
            application/json:
              schema:
                type:
                - array
                example: null
                items:
                  $ref: "#/components/schemas/ErrorDTO"
                  example: null
          description: The requested Example was not found.
      summary: Update an existing Example.
      tags:
      - example-controller
  /example/search:
    get:
      operationId: searchExamples
      parameters:
      - in: query
        name: searchTerms
        required: true
        schema:
          type:
          - array
          example: null
          items:
            type:
            - string
            example: null
      - description: Zero-based page index (0..N)
        in: query
        name: page
        schema:
          default: 0
          example: null
      - description: The size of the page to be returned
        in: query
        name: size
        schema:
          default: 20
          example: null
      - description: "Sorting criteria in the format: property,(asc|desc). Default\
          \ sort order is ascending. Multiple sort criteria are supported."
        in: query
        name: sort
        schema:
          type:
          - array
          example: null
          items:
            example: null
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PageDetailsExampleDTO"
                example: null
          description: The Example list has been successfully returned based on the
            search terms.
      summary: Gets paginated and sorted Examples based the search terms.
      tags:
      - example-controller
  /example/statistics:
    get:
      operationId: getWordStatistics
      responses:
        "200":
          content:
            application/json:
              schema:
                type:
                - object
                additionalProperties:
                  type:
                  - integer
                  format: int32
                  example: null
                example: null
          description: The word count map.
      summary: Returns the number of words for each user in order of cardinality.
      tags:
      - example-controller
  /example/{id}:
    delete:
      operationId: deleteExample
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type:
          - integer
          format: int64
          example: null
      responses:
        "204":
          description: No Content
      summary: Deletes an Example by its id.
      tags:
      - example-controller
    get:
      operationId: getExample
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type:
          - integer
          format: int64
          example: null
      responses:
        "200":
          content:
            application/json:
              schema:
                type:
                - array
                example: null
                items:
                  $ref: "#/components/schemas/ExampleDTO"
                  example: null
          description: The requested Example has been successfully returned.
        "404":
          content:
            application/json:
              schema:
                type:
                - array
                example: null
                items:
                  $ref: "#/components/schemas/ErrorDTO"
                  example: null
          description: The requested Example was not found.
      summary: Gets Example by its id.
      tags:
      - example-controller
components:
  schemas:
    ErrorDTO:
      type:
      - object
      example: null
      properties:
        details:
          example: null
        id:
          type:
          - string
          example: null
        message:
          type:
          - string
          example: null
        stackTrace:
          type:
          - string
          example: null
      required:
      - id
      - message
    ExampleDTO:
      type:
      - object
      example: null
      properties:
        createdDate:
          type:
          - string
          format: date-time
          example: null
        id:
          type:
          - integer
          format: int64
          example: null
        name:
          type:
          - string
          example: null
          maxLength: 20
          minLength: 3
      required:
      - name
    PageDetailsExampleDTO:
      type:
      - object
      example: null
      properties:
        content:
          type:
          - array
          example: null
          items:
            $ref: "#/components/schemas/ExampleDTO"
            example: null
        pageNumber:
          type:
          - integer
          format: int32
          example: null
        pageSize:
          type:
          - integer
          format: int32
          example: null
        sortOrders:
          type:
          - array
          example: null
          items:
            $ref: "#/components/schemas/SortOrder"
            example: null
        sorted:
          type:
          - boolean
          example: null
        totalElements:
          type:
          - integer
          format: int64
          example: null
        totalPages:
          type:
          - integer
          format: int32
          example: null
      required:
      - content
      - pageNumber
      - pageSize
      - sortOrders
      - sorted
      - totalElements
      - totalPages
    SortOrder:
      type:
      - object
      example: null
      properties:
        direction:
          type:
          - string
          example: null
        property:
          type:
          - string
          example: null
      required:
      - direction
      - property
