openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- description: Generated server url
  url: http://localhost:8080
paths:
  /example:
    get:
      operationId: getExamples
      parameters:
      - description: Zero-based page index (0..N)
        in: query
        name: page
        schema:
          type: integer
          default: 0
      - description: The size of the page to be returned
        in: query
        name: size
        schema:
          type: integer
          default: 20
      - description: "Sorting criteria in the format: property,(asc|desc). Default\
          \ sort order is ascending. Multiple sort criteria are supported."
        in: query
        name: sort
        schema:
          type: array
          items:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageDetailsExampleDTO'
          description: The Example list has been successfully returned.
      summary: Gets paginated and sorted Examples.
      tags:
      - example-controller
    post:
      operationId: createExample
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExampleDTO'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ExampleDTO'
          description: Example successfully created.
      summary: Creates a new Example.
      tags:
      - example-controller
    put:
      operationId: updateExample
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExampleDTO'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ExampleDTO'
          description: Example successfully updated.
        "404":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ErrorDTO'
          description: The requested Example was not found.
      summary: Update an existing Example.
      tags:
      - example-controller
  /example/search:
    get:
      operationId: searchExamples
      parameters:
      - in: query
        name: searchTerms
        required: true
        schema:
          type: array
          items:
            type: string
      - description: Zero-based page index (0..N)
        in: query
        name: page
        schema:
          type: integer
          default: 0
      - description: The size of the page to be returned
        in: query
        name: size
        schema:
          type: integer
          default: 20
      - description: "Sorting criteria in the format: property,(asc|desc). Default\
          \ sort order is ascending. Multiple sort criteria are supported."
        in: query
        name: sort
        schema:
          type: array
          items:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageDetailsExampleDTO'
          description: The Example list has been successfully returned based on the
            search terms.
      summary: Gets paginated and sorted Examples based the search terms.
      tags:
      - example-controller
  /example/statistics:
    get:
      operationId: getWordStatistics
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: integer
                  format: int32
          description: The word count map.
      summary: Returns the number of words for each user in order of cardinality.
      tags:
      - example-controller
  /example/{id}:
    delete:
      operationId: deleteExample
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "204":
          description: No Content
      summary: Deletes an Example by its id.
      tags:
      - example-controller
    get:
      operationId: getExample
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ExampleDTO'
          description: The requested Example has been successfully returned.
        "404":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ErrorDTO'
          description: The requested Example was not found.
      summary: Gets Example by its id.
      tags:
      - example-controller
components:
  schemas:
    ErrorDTO:
      type: object
      properties:
        details:
          type: object
        id:
          type: string
        message:
          type: string
        stackTrace:
          type: string
      required:
      - id
      - message
    ExampleDTO:
      type: object
      properties:
        createdDate:
          type: string
          format: date-time
        id:
          type: integer
          format: int64
        name:
          type: string
          maxLength: 20
          minLength: 3
      required:
      - name
    PageDetailsExampleDTO:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/ExampleDTO'
        pageNumber:
          type: integer
          format: int32
        pageSize:
          type: integer
          format: int32
        sortOrders:
          type: array
          items:
            $ref: '#/components/schemas/SortOrder'
        sorted:
          type: boolean
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
          format: int32
      required:
      - content
      - pageNumber
      - pageSize
      - sortOrders
      - sorted
      - totalElements
      - totalPages
    SortOrder:
      type: object
      properties:
        direction:
          type: string
        property:
          type: string
      required:
      - direction
      - property
