scrape_configs:
  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: '10s'
    static_configs:
      - targets: ['server:8080']
        labels:
          application: 'template-app'
