app.stack.trace.enabled=false

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.metrics.web.server.request.autotime.enabled=false

management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.sla.http.server.requests=10ms,30ms

info.app.name=@parent.artifactId@
info.app.version=@project.version@
info.app.java.version=${java.runtime.version}
info.app.kotlin.version=@kotlin.version@
