{
 "title": "HTTP traffic",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": { "query": "label_values(application)" } },
   {
    "name": "version",
    "label": "Version",
    "query": {
     "query": "label_values(application_started_time_milliseconds,app_version)"
    }
   },
   {
    "name": "percentile",
    "label": "Percentile",
    "query": "99% : 0.99, 97% : 0.97, 95% : 0.95, 90% : 0.9, 50% : 0.5,"
   },
   {
    "name": "uri",
    "label": "URI",
    "query": {
     "query": "label_values(http_server_requests_milliseconds_count,uri)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Average latency since startup",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_milliseconds_sum{application=\"$application\", app_version=~\"$version\"})\r\n/\r\nsum(http_server_requests_milliseconds_count{application=\"$application\", app_version=~\"$version\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average latency",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_milliseconds_sum{application=\"$application\", app_version=~\"$version\"}[5m]))\r\n/\r\nsum(rate(http_server_requests_milliseconds_count{application=\"$application\", app_version=~\"$version\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$percentile Average latency since startup",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n    $percentile, sum by(le) (\r\n        http_server_requests_milliseconds_bucket{application=\"$application\", app_version=~\"$version\", uri!=\"/**\"}\r\n    )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$percentile Average latency",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n    $percentile, sum by(le) (\r\n        rate(http_server_requests_milliseconds_bucket{application=\"$application\", app_version=~\"$version\", uri!=\"/**\"}[5m])\r\n    )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_milliseconds_count{application=\"$application\", app_version=~\"$version\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Percentile latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "$percentile Percentile latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum by(le, method, uri) (rate(http_server_requests_milliseconds_bucket{application=\"$application\", app_version=~\"$version\", uri!=\"/**\", uri=~\"$uri\"}[5m])))",
     "legendFormat": "{{method}} - {{uri}}"
    }
   ]
  },
  {
   "title": "Percentile latency by method and endpoint",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, method, uri) (rate(http_server_requests_milliseconds_bucket{application=\"$application\", app_version=~\"$version\", uri!=\"/**\", uri=~\"$uri\"}[5m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le, method, uri) (rate(http_server_requests_milliseconds_bucket{application=\"$application\", app_version=~\"$version\", uri!=\"/**\", uri=~\"$uri\"}[5m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, method, uri) (rate(http_server_requests_milliseconds_bucket{application=\"$application\", app_version=~\"$version\", uri!=\"/**\", uri=~\"$uri\"}[5m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, method, uri) (rate(http_server_requests_milliseconds_bucket{application=\"$application\", app_version=~\"$version\", uri!=\"/**\", uri=~\"$uri\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Request latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Request latency by method and endpoint",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (method, uri) (\r\n    rate(http_server_requests_milliseconds_sum{application=\"$application\", app_version=~\"$version\", uri!=\"/**\", uri=~\"$uri\"}[5m])\r\n)\r\n/\r\nsum by (method, uri) (\r\n    rate(http_server_requests_milliseconds_count{application=\"$application\", app_version=~\"$version\", uri!=\"/**\", uri=~\"$uri\"}[5m])\r\n)",
     "legendFormat": "{{method}} - {{uri}}"
    }
   ]
  },
  {
   "title": "Top 10 request latencies",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(10,\r\n    sum by (method, uri) (rate(http_server_requests_milliseconds_sum{application=\"$application\", app_version=~\"$version\", uri!=\"/**\"}[5m]))\r\n    /\r\n    sum by (method, uri) (rate(http_server_requests_milliseconds_count{application=\"$application\", app_version=~\"$version\", uri!=\"/**\"}[5m]))\r\n    )",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Request rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Request rate per method and endpoint",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (method, uri) (\r\n    rate(http_server_requests_milliseconds_count{application=\"$application\", app_version=~\"$version\", uri=~\"$uri\"}[5m])\r\n)",
     "legendFormat": "{{method}} - {{uri}}"
    }
   ]
  },
  {
   "title": "Top 10 request rates",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(10, sum by (method, uri) (rate(http_server_requests_milliseconds_count{application=\"$application\", app_version=~\"$version\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}