{
 "title": "Method execution",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": { "query": "label_values(application)" } },
   {
    "name": "version",
    "label": "Version",
    "query": {
     "query": "label_values(application_started_time_milliseconds,app_version)"
    }
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": {
     "query": "label_values(app_method_executions_milliseconds_count,topic)"
    }
   },
   {
    "name": "method",
    "label": "Method",
    "query": {
     "query": "label_values(app_method_executions_milliseconds_count,method)"
    }
   },
   {
    "name": "percentile",
    "label": "Percentile",
    "query": "99% : 0.99, 97% : 0.97, 95% : 0.95, 90% : 0.9, 50% : 0.5,"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Average execution time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(app_method_executions_milliseconds_sum{application=\"$application\", app_version=~\"$version\", topic=~\"$topic\", method=~\"$method\"}) / sum(app_method_executions_milliseconds_count{application=\"$application\", app_version=~\"$version\", topic=~\"$topic\", method=~\"$method\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$percentile Average execution time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(histogram_quantile($percentile, sum by(le, method, topic) (app_method_executions_milliseconds_bucket{application=\"$application\", app_version=~\"$version\", topic=~\"$topic\", method=~\"$method\"})))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maximum average execution time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(sum(rate(app_method_executions_milliseconds_sum{application=\"$application\", app_version=~\"$version\", topic=~\"$topic\", method=~\"$method\"}[1m])) / sum(rate(app_method_executions_milliseconds_count{application=\"$application\", app_version=~\"$version\", topic=~\"$topic\", method=~\"$method\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Percentile execution time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "$percentile Percentile execution time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum by(le, method, topic) (rate(app_method_executions_milliseconds_bucket{application=\"$application\", app_version=~\"$version\", topic=~\"$topic\", method=~\"$method\"}[1m])))",
     "legendFormat": "{{topic}} - {{method}}"
    }
   ]
  },
  {
   "title": "Percentile execution time by method",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, method, topic) (rate(app_method_executions_milliseconds_bucket{application=\"$application\", app_version=~\"$version\", topic=~\"$topic\", method=~\"$method\"}[1m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le, method, topic) (rate(app_method_executions_milliseconds_bucket{application=\"$application\", app_version=~\"$version\", topic=~\"$topic\", method=~\"$method\"}[1m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, method, topic) (rate(app_method_executions_milliseconds_bucket{application=\"$application\", app_version=~\"$version\", topic=~\"$topic\", method=~\"$method\"}[1m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, method, topic) (rate(app_method_executions_milliseconds_bucket{application=\"$application\", app_version=~\"$version\", topic=~\"$topic\", method=~\"$method\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Execution time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Execution time by method",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (method, topic) (rate(app_method_executions_milliseconds_sum{application=\"$application\", app_version=~\"$version\", topic=~\"$topic\", method=~\"$method\"}[1m])) / sum by (method, topic) (rate(app_method_executions_milliseconds_count{application=\"$application\", app_version=~\"$version\", topic=~\"$topic\", method=~\"$method\"}[1m]))",
     "legendFormat": "{{topic}} - {{method}}"
    }
   ]
  },
  {
   "title": "Top 10 method executions",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(10, sum by (topic, method) (rate(app_method_executions_milliseconds_sum{application=\"$application\", app_version=~\"$version\", topic=~\"$topic\", method=~\"$method\"}[1m])) / sum by (topic, method) (rate(app_method_executions_milliseconds_count{application=\"$application\", app_version=~\"$version\", topic=~\"$topic\", method=~\"$method\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Execution rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Execution rate per method",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (method, topic) (rate(app_method_executions_milliseconds_count{application=\"$application\", app_version=~\"$version\", topic=~\"$topic\", method=~\"$method\"}[1m]))",
     "legendFormat": "{{topic}} - {{method}}"
    }
   ]
  },
  {
   "title": "Top 10 execution rates",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(10, sum by (topic, method) (rate(app_method_executions_milliseconds_count{application=\"$application\", app_version=~\"$version\", topic=~\"$topic\", method=~\"$method\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}