{
 "title": "Cache",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": { "query": "label_values(application)" } },
   {
    "name": "version",
    "label": "Version",
    "query": {
     "query": "label_values(application_started_time_milliseconds,app_version)"
    }
   },
   {
    "name": "cache_manager",
    "label": "Cache manager",
    "query": {
     "query": "label_values(cache_size,cache_manager)"
    }
   },
   { "name": "cache", "label": "Cache name", "query": { "query": "label_values(cache_size,cache)" } }
  ]
 },
 "panels": [
  {
   "title": "Cache hit %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cache_gets_total{application=\"$application\", app_version=~\"$version\", cache_manager=~\"$cache_manager\", cache=~\"$cache\", result=\"hit\"}) / sum(cache_gets_total{application=\"$application\", app_version=~\"$version\", cache_manager=~\"$cache_manager\", cache=~\"$cache\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache hit rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 20, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(cache_gets_total{application=\"$application\", app_version=~\"$version\", cache_manager=~\"$cache_manager\", cache=~\"$cache\", result=\"hit\"}) /\r\nsum(cache_gets_total{application=\"$application\", app_version=~\"$version\", cache_manager=~\"$cache_manager\", cache=~\"$cache\"})\r\n* 100",
     "legendFormat": "Hit"
    },
    {
     "expr": "sum(cache_gets_total{application=\"$application\", app_version=~\"$version\", cache_manager=~\"$cache_manager\", cache=~\"$cache\", result=\"miss\"}) /\r\nsum(cache_gets_total{application=\"$application\", app_version=~\"$version\", cache_manager=~\"$cache_manager\", cache=~\"$cache\"})\r\n* 100",
     "legendFormat": "Miss"
    }
   ]
  },
  {
   "title": "Cache miss %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cache_gets_total{application=\"$application\", app_version=~\"$version\", cache_manager=~\"$cache_manager\", cache=~\"$cache\", result=\"miss\"}) / sum(cache_gets_total{application=\"$application\", app_version=~\"$version\", cache_manager=~\"$cache_manager\", cache=~\"$cache\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cache_size{application=\"$application\", app_version=~\"$version\", cache_manager=~\"$cache_manager\", cache=~\"$cache\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 10 },
   "targets": [
    {
     "expr": "cache_size{application=\"$application\", app_version=~\"$version\", cache_manager=~\"$cache_manager\", cache=~\"$cache\"}",
     "legendFormat": "{{cache}}"
    }
   ]
  },
  {
   "title": "Cache eviction",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cache_evictions_total{application=\"$application\", app_version=~\"$version\", cache_manager=~\"$cache_manager\", cache=~\"$cache\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache eviction",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 16 },
   "targets": [
    {
     "expr": "cache_evictions_total{application=\"$application\", app_version=~\"$version\", cache_manager=~\"$cache_manager\", cache=~\"$cache\"}",
     "legendFormat": "{{cache}}"
    }
   ]
  }
 ]
}