{
 "title": "Exceptions & errors",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(jvm_classes_loaded,instance)"
    }
   },
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(jvm_classes_loaded,application)"
    }
   },
   {
    "name": "version",
    "label": "Version",
    "query": {
     "query": "label_values(application_started_time_milliseconds,app_version)"
    }
   },
   { "name": "exceptionId", "label": "ExceptionID filter" },
   {
    "name": "knownExceptionIds",
    "label": "Hide exceptions",
    "query": "9e4198cbdddec8e,8cffd898e0f96f1,1f719ad1a38082a"
   }
  ]
 },
 "panels": [
  {
   "title": "Total exceptions",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(app_exception_counter_total{application=\"$application\", app_version=~\"$version\", exceptionId!~\"$knownExceptionIds\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exceptions by type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 21, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "app_exception_counter_total{application=\"$application\", app_version=~\"$version\", exceptionId=~\".*$exceptionId.*\", exceptionId!~\"$knownExceptionIds\"}",
     "legendFormat": "{{exceptionId}} - {{exceptionType}}"
    }
   ]
  },
  {
   "title": "Exceptions per second",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "irate(app_exception_counter_total{application=\"$application\", app_version=~\"$version\", exceptionId=~\".*$exceptionId.*\", exceptionId!~\"$knownExceptionIds\"}[1m])",
     "legendFormat": "{{exceptionId}} - {{exceptionType}}"
    }
   ]
  },
  {
   "title": "Known exceptions",
   "type": "text",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 21 },
   "options": {
    "content": "| ExceptionID | ExceptionType | Comment |\n|-------------|---------------|---------|\n| 1f719ad1a38082a, 9e4198cbdddec8e |  IdNotFoundException | Wrong resource id was provided. |"
   }
  }
 ]
}