name: CI build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B verify -ntp

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: jacoco-report/target/site/jacoco-aggregate/

      - name: Upload JaCoCo report to Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: jacoco-report/target/site/jacoco-aggregate/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
