name: CI build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B verify -ntp

      - name: Get app version
        id: get_version
        run: |
          version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "app_version=${version}" >> $GITHUB_OUTPUT

      - name: Lint Dockerfile
        run: |
          docker run --rm -i ghcr.io/hadolint/hadolint < Dockerfile

      - name: Build the Docker image
        id: build_image
        run: |
          image_tag=${{ github.repository }}:${{ steps.get_version.outputs.app_version }}
          echo "image_tag=${image_tag}" >> $GITHUB_OUTPUT
          
          docker build . --file Dockerfile --tag ${image_tag}

          if [ "${GITHUB_REF}" = "refs/heads/main" ]; then
            docker tag ${image_tag} ${{ github.repository }}:latest
          fi

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.12.0
        with:
          image-ref: '${{ steps.build_image.outputs.image_tag }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'